apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: ossm-example-headers-extension
spec:
  pluginConfig:
    my-key: my-wasm-value
  url: oci://quay.io/isanchez/ossm-example-headers-extension:1.0.0
  priority: 100
  phase: STATS
  selector:
    matchLabels:
      app: httpbin
